### PR TITLE
Rename gradient 39 from Deep Blue to Deep Blue 2

### LINKED ISSUE #6: Deep Blue
Both [16](https://github.com/itmeo/webgradients/blob/master/webgradients.css#L77) and [39](https://github.com/itmeo/webgradients/blob/master/webgradients.css#L192) are named `.deep_blue`.

### PR DESCRIPTION
**Pull request by torarnv**
Avoids naming conflicts. Fixes #6

### CODE REVIEW

**Comment by torarnv** [comment]
As a followup the website needs to be updated. Don't know where the sources for that are

**Comment by torarnv** [comment]
@joeworkman

**Comment by torarnv** [comment]
@alexanderisora

**Comment by cruisediary** [comment]
@alexanderisora any update?

**Comment by alexanderisora** [comment]
@joeworkman @cruisediary thank you guys for your care but I've left the organisation months ago.

**Comment by torarnv** [comment]
@dimablover ping, you seem to be the only one in the @itmeo organization still

**Pull request closed without merging**
